apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: fintech
data:
  API_URL: "http://api-gateway.fintech.svc.cluster.local"
  AUTH_SERVICE_URL: "http://auth-service.fintech.svc.cluster.local"
